app_auth/urls.py
from django.urls import path
from .views  import *

urlpatterns = [
    path('login', login_blog, name= "login-blog"),
    path('register', register, name= "register"),
    path('logout', logout_blog, name= "logout"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name= "home")
]

my_admin_panel/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', appadmin, name='appadmin'),
    path('my-articles', user_article, name='my-articles'),

]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import home, detail, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name= "home"),
    path('article/<int:id_article>', detail, name = "detail"),
    path('article/recherche', search, name = "search"),
    path('auth/',include("app_auth.urls")),
    path('app-admin/',include("my_admin_panel.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_auth/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    desc = models.TextField()
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    upload_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

my_admin_panel/models.py
from django.db import models

# Create your models here.

app_auth/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
class RegisterForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    pwd_confirm = forms.CharField(label="Mot de passe de confirmation", widget=forms.PasswordInput(attrs={'class':'form-control'}))

app_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *


def login_blog(request):
    if request.method == "POST":
      form = LoginForm(request.POST)
      if form.is_valid():
        username = form.cleaned_data['username']
        pwd = form.cleaned_data['pwd']
        user = authenticate(username=username, password=pwd)
        if user is not None:
          login(request, user)
   
          return redirect('home')
        else:
          messages.error(request,"Authentification echouée")
          return render(request, 'login.html', {'form':form})
      else:
          for field in form.errors:
            form[field].field.widget.attrs['class'] += ' is-invalid'
          return render(request, 'login.html', {'form': form})

          
      
    else:
        form = LoginForm()
        return render(request, "login.html", {'form': form})
            

def register(request):
  if request.method == 'POST':
    form = RegisterForm(request.POST)
    if form.is_valid():
      username = form.cleaned_data['username']
      pwd = form.cleaned_data['pwd']
      user = User.objects.create_user(username=username, password=pwd)
      if user is not None:
        return redirect("login-blog")
      else:
        messages.error(request,'Creation à échouée!')
        return render(request, 'register.html', {'form':form})
    else:
        return render(request, 'register.html', {'form':form})
    return render(request, 'register.html', {})

  form = RegisterForm()
  return render(request, 'register.html', {'form':form})


def logout_blog(request):
  logout(request)
  return redirect("login-blog")

blog/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def home(request):
    list_articles = Article.objects.all()
    context = {'liste_articles':list_articles}
    return render(request, 'index.html', context)

def detail(request,id_article):
    article = Article.objects.get(id=id_article)
    category = article.category
    article_en_relation = Article.objects.filter(category=category)[:5]
    return render (request, 'detail.html',{'article': article, 'aer':article_en_relation})

def search(request):
    query = request.GET["article"]
    liste_article = Article.objects.filter(title__contains = query)
    return render (request, 'search.html', {"liste_article":liste_article})

my_admin_panel/views.py
from django.shortcuts import render
from blog.models import Article


def appadmin(request):
    return render(request, 'contenu.html')

def user_article(request):
    list_articles = Article.objects.filter(user=request.user)
    return render(request, 'my-articles.html', {'list_articles':list_articles})

app_auth/templates/login.html
{% extends 'base.html' %}
{% block title %}
  Connexion au Blog
{% endblock %}

{% block content %}
  <h2>Connexion</h2>
  <div class="container">
    <div class="col-md-12 mt-5">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-danger text-center">
            <strong>{{ message }}</strong>
          </div>
        {% endfor %}
      {% endif %}

      <form action="" method="POST" novalidate>
        {% csrf_token %}
        <div class="card">
          <div class="card-header text-center">
            <i class="fas fa-user"></i> Connexion au Blog
          </div>
          <div class="card-body">
            <label for="id_username">Nom d'utilisateur</label>
            {% if form.username.errors %}
              {% for error in form.username.errors %}
                <div class="div-error-{{form.username.name}}">
                  <small class="text-danger">{{ error }}</small>
                </div>
              {% endfor %}
            {% endif %}
            {{ form.username }}

            <label for="id_pwd">Mot de passe</label>
            {% if form.pwd.errors %}
              {% for error in form.pwd.errors %}
                <div class="div-error-{{form.pwd.name}}">
                  <small class="text-danger">{{ error }}</small>
                </div>
              {% endfor %}
            {% endif %}
            {{ form.pwd }}
          </div>
          <div class="card-footer">
            <button class="btn btn-primary btn-block">Se connecter</button>
            <p class="mt-2">Vous n'avez pas de compte ? <a href="{% url 'register'%}">Creer votre Compte</a></p>
          </div>
       
        </div>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(document).ready(function () {
      $('input').keyup(function () {
        let textSaisi = $(this).val();
        if (textSaisi === '') {
          if (!$(this).hasClass('is-invalid')) {
            $(this).addClass('is-invalid');
          } else {
            $(this).removeClass('is-invalid');
          }
        }
      })
    })
  </script>
{% endblock %}

app_auth/templates/register.html
{% extends 'base.html' %}
{% block title %}
 Creation du compte au Blog
{% endblock %}

{% block content %}
  <h2>Connexion</h2>
  <div class="container">
    <div class="col-md-12 mt-5">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-danger text-center">
            <strong>{{ message }}</strong>
          </div>
        {% endfor %}
      {% endif %}

      <form action="" method="POST" novalidate>
        {% csrf_token %}
        <div class="card">
          <div class="card-header text-center">
            <i class="fas fa-user-lock"></i> Creation du compte 
          </div>
          <div class="card-body">
            {{form}}


          </div>
          <div class="card-footer">
            <button class="btn btn-primary btn-block">Creer le compte</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
 
{% endblock %}

blog/templates/_footer.html
<!-- Footer -->
<footer class="bg-dark text-light py-4 text-center  mt-5 ">
    <!-- Grid container -->
    <div class="container p-4">
      <!-- Section: Social media -->
      <section class="mb-4 ">
        <!-- Facebook -->
        <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>
  
        <!-- Github -->
        <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
  
      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Sign up for our newsletter</strong>
              </p>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="email" id="form5Example24" class="form-control" />
                <label class="form-label" for="form5Example24">Email address</label>
              </div>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button data-mdb-ripple-init type="submit" class="btn btn-outline mb-4">
                Subscribe
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
  
      <!-- Section: Text -->
      <section class="mb-4">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
          repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam eum
          harum corrupti dicta, aliquam sequi voluptate quas.
        </p>
      </section>
      <!-- Section: Text -->
  
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a class="text-body" href="#!">Link 1</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 2</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 3</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a class="text-body" href="#!">Link 1</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 2</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 3</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a class="text-body" href="#!">Link 1</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 2</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 3</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a class="text-body" href="#!">Link 1</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 2</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 3</a>
              </li>
              <li>
                <a class="text-body" href="#!">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2020 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

blog/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">My blog</a>
    <button
      data-mdb-collapse-init
      class="navbar-toggler"
      type="button"
      data-mdb-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled"
            >Mon Compte</a
          >
        </li>
      </ul>
      {%if user.is_authenticated%}
      <a href="{% url 'logout' %}" class="btn btn-info">Déconnexion</a>
      {%else%}
      <a href="{% url 'login-blog' %}" class="btn btn-info">Connexion</a>
      {% endif %}
      <form class="d-flex input-group w-auto" action="{% url 'search'%}">
        <input
          type="text"
          class="form-control"
          placeholder="Recherche"
          aria-label="Search"
          name="article"
        />

      </form>
    </div>
  </div>
</nav>

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Blog {% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
</head>
<body>
    {% include '_nav.html'%}

    {% block content %}

    {% endblock %}

    {% include '_footer.html'%}
    <!-- MDB -->
    <script type="text/javascript" src="{% static "js/mdb.umd.min.js" %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>


    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-390EEJZXKP"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-390EEJZXKP');
</script>

{% block scripts%}

{% endblock  %}

</body>
</html>

blog/templates/detail.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="text-center mt-2">Détail article</h1>
            <img src="{{article.image.url}}" alt="image article" style="max-width: 600px">
            <h2>{{article.title}}</h2>
            <p>{{article.desc}}</p>
        </div>
        <div class="col-md-4">
            <h3 class="mt-2">Les articles en relations</h3 class="mt-2">
            <div class="row">
                {%for art in aer%}
                {%if art.id != article.id%}
          
                <div class="col-md-7 mb-1">
                    <a href="{% url 'detail' art.id %}">
                        <img src="{{ art.image.url }}" alt="" style="max-width: 180px;">
                    </a>
                    
                    
                  
                </div>
                <div class="col-5">
                    <strong><a href="{% url 'detail' art.id %}">{{art.title}}</a></strong> <br>
                    {{art.desc|truncatewords:7}}
                </div>
  
                {%endif%}
                {%endfor%}

            </div>

        </div>
    </div>

</div>

{% endblock %}

blog/templates/index.html
{% extends 'base.html'%}
{% block content %}
<!-- Start your project here-->
<h1 class="text-center mt-3">Bienvenue sur notre blog</h1>
<div class="container">
  <div class="row">
    {% for article in liste_articles%}
    <div class="card col-12 col-md-6  col-lg-3 col-xl-3">

      <div class="card" style="height: 240 px">
        <div class="bg-image hover-overlay" data-mdb-ripple-init data-mdb-ripple-color="light">
          <img src=" {{ article.image.url}}" class="img-fluid" alt="image non chargée" style="height: 200px;" />
          <a href="{% url 'detail' article.id %}">
            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
          </a>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <a href="{% url 'detail' article.id %}">{{article.title}}</a></h5>
          <p class="card-text">{{article.desc|truncatewords:8}}</p>
          <p class="card-text"> Publié il y'a {{article.created_at|timesince}}</p>
          <a href="{% url 'detail' article.id %}" class="btn btn-primary" data-mdb-ripple-init>Lire la suite</a>
        </div>
      </div>


    </div>

    {%endfor%}


  </div>
</div>

<!-- End your project here-->
{% endblock %}

blog/templates/search.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}

  <div class="container">
    <h2>Liste de recherche</h2>
    <div class="row">
      {% for article in liste_article %}
        <div class="card col-12 col-md-6 col-lg-3 col-xl-3">
          <div class="card" style="height: 240 px">
            <div class="bg-image hover-overlay" data-mdb-ripple-init data-mdb-ripple-color="light">
              <img src=" {{ article.image.url }}" class="img-fluid" alt="image non chargée" style="height: 200px;" />
              <a href="{% url 'detail' article.id %}"><div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div></a>
            </div>
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'detail' article.id %}">{{ article.title }}</a></h5>
              <p class="card-text">{{ article.desc|truncatewords:8 }}</p>
              <p class="card-text">Publié il y'a {{ article.created_at|timesince }}</p>
              <a href="{% url 'detail' article.id %}" class="btn btn-primary" data-mdb-ripple-init>Lire la suite</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

my_admin_panel/templates/_nav-admin.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        data-mdb-collapse-init
        class="navbar-toggler"
        type="button"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="{url  ''}">Admin
  
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'my-article' %}">Mes articles</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->
  
      <!-- Right elements -->
      <div class="d-flex align-items-center">

        <!-- Notifications -->
        <ul class="navbar-nav ml-auto nav-flex-icons">
          {% if user.is_authenticated %}
          <li class="nav-item"> 
           
            <span class="nav-link"> {{user.username}} </span>
      
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded = "false"
            > <i class="fas fa-user"></i>
    
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-default"
          arira-labelledby="navbarDropdownMenuLink-333">
          {% if user.is_authenticated %}
          <a class="dropdown-item" href="#">Deconnexion</a>
          {% endif %}
      

        </div>

          </li>


        </ul>
    
    
       
        
      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->

my_admin_panel/templates/contenu.html
{% extends 'contenu/base.html' %}
{% block Title %} Page admin{% endblock Title %}
{% block content %}
<div class="row">
    <div class="container"></div>
    <h2> page d'administration</h2>
</div>
{% endblock content %}

my_admin_panel/templates/contenu/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block Title %} admin {% endblock Title %}</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />

</head>
<body>
    {% include '_nav-admin.html' %}
    <h1>Base de donnée</h1>
    {% block content %}

    {% endblock  %}

    <script src="{% static 'blog/js/jquery.js'%}"></script>
    <script src="{% static 'blog/js/bootstrap.js'%}"></script>
    <script src="{% static 'blog/js/popper.js'%}"></script>
</body>
</html>

my_admin_panel/templates/my-articles.html
{% extends 'contenu/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12"></div>
        {% for article in list_articles  %}
        <h2> {{article.title}}</h2>
        {% endfor %}
 
    </div>

</div>
{% endblock content %}